"""Structured linear algebra and Gaussian primitives for JAX."""

__version__ = "0.0.8"

from gaussx._distributions._conditional import conditional as conditional
from gaussx._distributions._kl import dist_kl_divergence as dist_kl_divergence
from gaussx._expfam import (
    GaussianExpFam as GaussianExpFam,
    fisher_info as fisher_info,
    kl_divergence as kl_divergence,
    log_partition as log_partition,
    sufficient_stats as sufficient_stats,
    to_expectation as to_expectation,
    to_natural as to_natural,
)
from gaussx._operators import (
    BlockDiag as BlockDiag,
    BlockTriDiag as BlockTriDiag,
    ImplicitCrossKernelOperator as ImplicitCrossKernelOperator,
    ImplicitKernelOperator as ImplicitKernelOperator,
    InterpolatedOperator as InterpolatedOperator,
    KernelOperator as KernelOperator,
    Kronecker as Kronecker,
    KroneckerSum as KroneckerSum,
    LowerBlockTriDiag as LowerBlockTriDiag,
    LowRankUpdate as LowRankUpdate,
    MaskedOperator as MaskedOperator,
    ProductOperator as ProductOperator,
    ScaledOperator as ScaledOperator,
    SumKronecker as SumKronecker,
    SumOperator as SumOperator,
    SVDLowRankUpdate as SVDLowRankUpdate,
    Toeplitz as Toeplitz,
    UpperBlockTriDiag as UpperBlockTriDiag,
    implicit_cross_kernel as implicit_cross_kernel,
    low_rank_plus_diag as low_rank_plus_diag,
    low_rank_plus_identity as low_rank_plus_identity,
    svd_low_rank_plus_diag as svd_low_rank_plus_diag,
)
from gaussx._primitives import (
    cholesky as cholesky,
    diag as diag,
    eig as eig,
    eigvals as eigvals,
    inv as inv,
    logdet as logdet,
    solve as solve,
    sqrt as sqrt,
    svd as svd,
    trace as trace,
)
from gaussx._recipes import (
    FilterState as FilterState,
    GaussianSites as GaussianSites,
    LOVECache as LOVECache,
    base_conditional as base_conditional,
    conditional_interpolate as conditional_interpolate,
    cvi_update_sites as cvi_update_sites,
    ensemble_covariance as ensemble_covariance,
    ensemble_cross_covariance as ensemble_cross_covariance,
    expectation_to_natural as expectation_to_natural,
    expectations_to_ssm as expectations_to_ssm,
    gauss_kl as gauss_kl,
    kalman_filter as kalman_filter,
    kalman_gain as kalman_gain,
    kronecker_mll as kronecker_mll,
    kronecker_posterior_predictive as kronecker_posterior_predictive,
    love_cache as love_cache,
    love_variance as love_variance,
    natural_to_expectation as natural_to_expectation,
    naturals_to_ssm as naturals_to_ssm,
    rts_smoother as rts_smoother,
    sites_to_precision as sites_to_precision,
    spingp_log_likelihood as spingp_log_likelihood,
    spingp_posterior as spingp_posterior,
    ssm_to_expectations as ssm_to_expectations,
    ssm_to_naturals as ssm_to_naturals,
)
from gaussx._recipes._parallel_kalman import (
    parallel_kalman_filter as parallel_kalman_filter,
    parallel_rts_smoother as parallel_rts_smoother,
)
from gaussx._strategies import (
    AbstractSolverStrategy as AbstractSolverStrategy,
    AutoSolver as AutoSolver,
    BBMMSolver as BBMMSolver,
    CGSolver as CGSolver,
    ComposedSolver as ComposedSolver,
    DenseSolver as DenseSolver,
    LSMRSolver as LSMRSolver,
    PreconditionedCGSolver as PreconditionedCGSolver,
)
from gaussx._sugar import (
    add_jitter as add_jitter,
    batched_kernel_matvec as batched_kernel_matvec,
    batched_kernel_rmatvec as batched_kernel_rmatvec,
    blr_diag_update as blr_diag_update,
    blr_full_update as blr_full_update,
    cavity_distribution as cavity_distribution,
    center_kernel as center_kernel,
    centering_operator as centering_operator,
    conditional_variance as conditional_variance,
    cov_transform as cov_transform,
    cubature_points as cubature_points,
    damped_natural_update as damped_natural_update,
    diag_conditional_variance as diag_conditional_variance,
    gauss_hermite_points as gauss_hermite_points,
    gauss_newton_precision as gauss_newton_precision,
    gaussian_entropy as gaussian_entropy,
    gaussian_expected_log_lik as gaussian_expected_log_lik,
    gaussian_log_prob as gaussian_log_prob,
    ggn_diagonal as ggn_diagonal,
    hsic as hsic,
    hutchinson_hessian_diag as hutchinson_hessian_diag,
    joseph_update as joseph_update,
    kl_standard_normal as kl_standard_normal,
    log_marginal_likelihood as log_marginal_likelihood,
    mmd_squared as mmd_squared,
    newton_update as newton_update,
    nystrom_operator as nystrom_operator,
    process_noise_covariance as process_noise_covariance,
    project as project,
    quadratic_form as quadratic_form,
    rff_operator as rff_operator,
    riemannian_psd_correction as riemannian_psd_correction,
    schur_complement as schur_complement,
    sigma_points as sigma_points,
    stable_rbf_kernel as stable_rbf_kernel,
    stable_squared_distances as stable_squared_distances,
    svgp_variance_adjustment as svgp_variance_adjustment,
    trace_correction as trace_correction,
    trace_product as trace_product,
    unwhiten as unwhiten,
    variational_elbo_gaussian as variational_elbo_gaussian,
    variational_elbo_mc as variational_elbo_mc,
    whiten_covariance as whiten_covariance,
    whitened_svgp_predict as whitened_svgp_predict,
    woodbury_solve as woodbury_solve,
)
from gaussx._tags import (
    block_diagonal_tag as block_diagonal_tag,
    block_tridiagonal_tag as block_tridiagonal_tag,
    diagonal_tag as diagonal_tag,
    is_block_diagonal as is_block_diagonal,
    is_block_tridiagonal as is_block_tridiagonal,
    is_diagonal as is_diagonal,
    is_kronecker as is_kronecker,
    is_kronecker_sum as is_kronecker_sum,
    is_low_rank as is_low_rank,
    is_lower_triangular as is_lower_triangular,
    is_negative_semidefinite as is_negative_semidefinite,
    is_positive_semidefinite as is_positive_semidefinite,
    is_symmetric as is_symmetric,
    is_upper_triangular as is_upper_triangular,
    kronecker_sum_tag as kronecker_sum_tag,
    kronecker_tag as kronecker_tag,
    low_rank_tag as low_rank_tag,
    lower_triangular_tag as lower_triangular_tag,
    negative_semidefinite_tag as negative_semidefinite_tag,
    positive_semidefinite_tag as positive_semidefinite_tag,
    symmetric_tag as symmetric_tag,
    tridiagonal_tag as tridiagonal_tag,
    unit_diagonal_tag as unit_diagonal_tag,
    upper_triangular_tag as upper_triangular_tag,
)
from gaussx._uncertain import (
    AbstractIntegrator as AbstractIntegrator,
    AbstractLikelihood as AbstractLikelihood,
    AssumedDensityFilter as AssumedDensityFilter,
    GaussHermiteIntegrator as GaussHermiteIntegrator,
    GaussianLikelihood as GaussianLikelihood,
    GaussianState as GaussianState,
    MonteCarloIntegrator as MonteCarloIntegrator,
    PropagationResult as PropagationResult,
    TaylorIntegrator as TaylorIntegrator,
    UnscentedIntegrator as UnscentedIntegrator,
    cost_expectation as cost_expectation,
    elbo as elbo,
    expected_log_likelihood as expected_log_likelihood,
    gradient_expectation as gradient_expectation,
    kernel_expectations as kernel_expectations,
    log_likelihood_expectation as log_likelihood_expectation,
    mean_expectation as mean_expectation,
    uncertain_bgplvm_predict as uncertain_bgplvm_predict,
    uncertain_gp_predict as uncertain_gp_predict,
    uncertain_gp_predict_mc as uncertain_gp_predict_mc,
    uncertain_svgp_predict as uncertain_svgp_predict,
    uncertain_vgp_predict as uncertain_vgp_predict,
)


try:
    from gaussx._distributions import (
        MultivariateNormal as MultivariateNormal,
        MultivariateNormalPrecision as MultivariateNormalPrecision,
    )
except ModuleNotFoundError as _e:
    if _e.name != "numpyro":
        raise
