"""Structured linear algebra and Gaussian primitives for JAX."""

__version__ = "0.0.15"

# Import the non-numpyro helpers directly from submodules. Avoid
# ``from gaussx._distributions import ...`` so the optional numpyro guard
# at the bottom of this file remains the single entry point that handles
# missing numpyro.
from gaussx._distributions._conditional import conditional as conditional
from gaussx._distributions._gaussian import (
    add_jitter as add_jitter,
    gaussian_entropy as gaussian_entropy,
    gaussian_log_prob as gaussian_log_prob,
    kl_standard_normal as kl_standard_normal,
    quadratic_form as quadratic_form,
)
from gaussx._distributions._joseph import joseph_update as joseph_update
from gaussx._distributions._kl import dist_kl_divergence as dist_kl_divergence
from gaussx._distributions._project import project as project
from gaussx._expfam import (
    GaussianExpFam as GaussianExpFam,
    expectation_to_meanvar as expectation_to_meanvar,
    expectation_to_natural as expectation_to_natural,
    fisher_info as fisher_info,
    kl_divergence as kl_divergence,
    log_partition as log_partition,
    mean_cov_to_natural as mean_cov_to_natural,
    meanvar_to_expectation as meanvar_to_expectation,
    meanvar_to_natural as meanvar_to_natural,
    natural_to_expectation as natural_to_expectation,
    natural_to_mean_cov as natural_to_mean_cov,
    natural_to_meanvar as natural_to_meanvar,
    sufficient_stats as sufficient_stats,
    to_expectation as to_expectation,
    to_natural as to_natural,
)
from gaussx._gp import (
    LOOResult as LOOResult,
    LOVECache as LOVECache,
    PredictionCache as PredictionCache,
    base_conditional as base_conditional,
    build_prediction_cache as build_prediction_cache,
    collapsed_elbo as collapsed_elbo,
    conditional_interpolate as conditional_interpolate,
    gauss_kl as gauss_kl,
    kronecker_mll as kronecker_mll,
    kronecker_posterior_predictive as kronecker_posterior_predictive,
    leave_one_out_cv as leave_one_out_cv,
    love_cache as love_cache,
    love_variance as love_variance,
    oilmm_back_project as oilmm_back_project,
    oilmm_project as oilmm_project,
    predict_mean as predict_mean,
    predict_variance as predict_variance,
    svgp_variance_adjustment as svgp_variance_adjustment,
    unwhiten as unwhiten,
    unwhiten_covariance as unwhiten_covariance,
    variational_elbo_gaussian as variational_elbo_gaussian,
    variational_elbo_mc as variational_elbo_mc,
    whiten_covariance as whiten_covariance,
    whitened_svgp_predict as whitened_svgp_predict,
)
from gaussx._inference import (
    blr_diag_update as blr_diag_update,
    blr_full_update as blr_full_update,
    cavity_distribution as cavity_distribution,
    damped_natural_update as damped_natural_update,
    ensemble_covariance as ensemble_covariance,
    ensemble_cross_covariance as ensemble_cross_covariance,
    ensemble_kalman_gain as ensemble_kalman_gain,
    gauss_newton_precision as gauss_newton_precision,
    gaussian_expected_log_lik as gaussian_expected_log_lik,
    ggn_diagonal as ggn_diagonal,
    hutchinson_hessian_diag as hutchinson_hessian_diag,
    log_marginal_likelihood as log_marginal_likelihood,
    newton_update as newton_update,
    process_noise_covariance as process_noise_covariance,
    riemannian_psd_correction as riemannian_psd_correction,
    trace_correction as trace_correction,
)
from gaussx._kernels import (
    center_kernel as center_kernel,
    centering_operator as centering_operator,
    create_grid as create_grid,
    cubic_interpolation_weights as cubic_interpolation_weights,
    grid_data as grid_data,
    hsic as hsic,
    mmd_squared as mmd_squared,
    nystrom_operator as nystrom_operator,
    rff_operator as rff_operator,
)
from gaussx._linalg import (
    batched_kernel_matvec as batched_kernel_matvec,
    batched_kernel_rmatvec as batched_kernel_rmatvec,
    conditional_variance as conditional_variance,
    cov_transform as cov_transform,
    diag_conditional_variance as diag_conditional_variance,
    diag_inv as diag_inv,
    discrete_lyapunov_solve as discrete_lyapunov_solve,
    safe_cholesky as safe_cholesky,
    schur_complement as schur_complement,
    solve_columns as solve_columns,
    solve_matrix as solve_matrix,
    solve_rows as solve_rows,
    stable_rbf_kernel as stable_rbf_kernel,
    stable_squared_distances as stable_squared_distances,
    trace_product as trace_product,
    woodbury_solve as woodbury_solve,
)
from gaussx._operators import (
    BlockDiag as BlockDiag,
    BlockTriDiag as BlockTriDiag,
    ImplicitCrossKernelOperator as ImplicitCrossKernelOperator,
    ImplicitKernelOperator as ImplicitKernelOperator,
    InterpolatedOperator as InterpolatedOperator,
    KernelOperator as KernelOperator,
    Kronecker as Kronecker,
    KroneckerSum as KroneckerSum,
    KroneckerSumSqrt as KroneckerSumSqrt,
    LowerBlockTriDiag as LowerBlockTriDiag,
    LowRankUpdate as LowRankUpdate,
    MaskedOperator as MaskedOperator,
    ProductOperator as ProductOperator,
    ScaledOperator as ScaledOperator,
    SumKronecker as SumKronecker,
    SumOperator as SumOperator,
    SVDLowRankUpdate as SVDLowRankUpdate,
    Toeplitz as Toeplitz,
    ToeplitzCholesky as ToeplitzCholesky,
    UpperBlockTriDiag as UpperBlockTriDiag,
    implicit_cross_kernel as implicit_cross_kernel,
    kronecker_sum_sample as kronecker_sum_sample,
    low_rank_plus_diag as low_rank_plus_diag,
    low_rank_plus_identity as low_rank_plus_identity,
    sumkronecker_sample as sumkronecker_sample,
    svd_low_rank_plus_diag as svd_low_rank_plus_diag,
    toeplitz_sample as toeplitz_sample,
)
from gaussx._primitives import (
    DenseFallbackWarning as DenseFallbackWarning,
    RootDecomposition as RootDecomposition,
    SumKroneckerSqrt as SumKroneckerSqrt,
    cholesky as cholesky,
    cholesky_logdet as cholesky_logdet,
    diag as diag,
    eig as eig,
    eigvals as eigvals,
    inv as inv,
    logdet as logdet,
    root_decomposition as root_decomposition,
    root_inv_decomposition as root_inv_decomposition,
    solve as solve,
    sqrt as sqrt,
    submatrix as submatrix,
    svd as svd,
    trace as trace,
)
from gaussx._quadrature import (
    AbstractIntegrator as AbstractIntegrator,
    AbstractLikelihood as AbstractLikelihood,
    AnalyticalPsiStatistics as AnalyticalPsiStatistics,
    AssumedDensityFilter as AssumedDensityFilter,
    BernoulliLikelihood as BernoulliLikelihood,
    GaussHermiteIntegrator as GaussHermiteIntegrator,
    GaussianLikelihood as GaussianLikelihood,
    GaussianState as GaussianState,
    HeteroscedasticGaussianLikelihood as HeteroscedasticGaussianLikelihood,
    MonteCarloIntegrator as MonteCarloIntegrator,
    PoissonLikelihood as PoissonLikelihood,
    PropagationResult as PropagationResult,
    SoftmaxLikelihood as SoftmaxLikelihood,
    StudentTLikelihood as StudentTLikelihood,
    TaylorIntegrator as TaylorIntegrator,
    UnscentedIntegrator as UnscentedIntegrator,
    compute_psi_statistics as compute_psi_statistics,
    cost_expectation as cost_expectation,
    cubature_points as cubature_points,
    elbo as elbo,
    ep_tilted_moments as ep_tilted_moments,
    expected_log_likelihood as expected_log_likelihood,
    gauss_hermite_points as gauss_hermite_points,
    gradient_expectation as gradient_expectation,
    kernel_expectations as kernel_expectations,
    log_likelihood_expectation as log_likelihood_expectation,
    mean_expectation as mean_expectation,
    sigma_points as sigma_points,
    uncertain_bgplvm_predict as uncertain_bgplvm_predict,
    uncertain_gp_predict as uncertain_gp_predict,
    uncertain_gp_predict_mc as uncertain_gp_predict_mc,
    uncertain_svgp_predict as uncertain_svgp_predict,
    uncertain_vgp_predict as uncertain_vgp_predict,
)
from gaussx._ssm import (
    ConstantSDE as ConstantSDE,
    CosineSDE as CosineSDE,
    DAREResult as DAREResult,
    EmissionModel as EmissionModel,
    FilterState as FilterState,
    GaussianSites as GaussianSites,
    InfiniteHorizonState as InfiniteHorizonState,
    MaternSDE as MaternSDE,
    PeriodicSDE as PeriodicSDE,
    ProductSDE as ProductSDE,
    QuasiPeriodicSDE as QuasiPeriodicSDE,
    SDEKernel as SDEKernel,
    SDEParams as SDEParams,
    SumSDE as SumSDE,
    cavity_from_marginal as cavity_from_marginal,
    cvi_update_sites as cvi_update_sites,
    dare as dare,
    expectations_to_ssm as expectations_to_ssm,
    infinite_horizon_filter as infinite_horizon_filter,
    infinite_horizon_smoother as infinite_horizon_smoother,
    kalman_filter as kalman_filter,
    kalman_gain as kalman_gain,
    naturals_to_ssm as naturals_to_ssm,
    pairwise_marginals as pairwise_marginals,
    parallel_kalman_filter as parallel_kalman_filter,
    parallel_rts_smoother as parallel_rts_smoother,
    rts_smoother as rts_smoother,
    sde_autocovariance as sde_autocovariance,
    site_mean_var_from_natural as site_mean_var_from_natural,
    site_natural_from_tilted as site_natural_from_tilted,
    sites_to_precision as sites_to_precision,
    spingp_log_likelihood as spingp_log_likelihood,
    spingp_posterior as spingp_posterior,
    ssm_to_expectations as ssm_to_expectations,
    ssm_to_naturals as ssm_to_naturals,
)
from gaussx._strategies import (
    AbstractLogdetStrategy as AbstractLogdetStrategy,
    AbstractSolverStrategy as AbstractSolverStrategy,
    AbstractSolveStrategy as AbstractSolveStrategy,
    AutoSolver as AutoSolver,
    BBMMSolver as BBMMSolver,
    CGSolver as CGSolver,
    ComposedSolver as ComposedSolver,
    DenseLogdet as DenseLogdet,
    DenseSolver as DenseSolver,
    IndefiniteSLQLogdet as IndefiniteSLQLogdet,
    LSMRSolver as LSMRSolver,
    MINRESSolver as MINRESSolver,
    PreconditionedCGSolver as PreconditionedCGSolver,
    SLQLogdet as SLQLogdet,
)
from gaussx._tags import (
    block_diagonal_tag as block_diagonal_tag,
    block_tridiagonal_tag as block_tridiagonal_tag,
    diagonal_tag as diagonal_tag,
    is_block_diagonal as is_block_diagonal,
    is_block_tridiagonal as is_block_tridiagonal,
    is_diagonal as is_diagonal,
    is_kronecker as is_kronecker,
    is_kronecker_sum as is_kronecker_sum,
    is_low_rank as is_low_rank,
    is_lower_triangular as is_lower_triangular,
    is_negative_semidefinite as is_negative_semidefinite,
    is_positive_semidefinite as is_positive_semidefinite,
    is_symmetric as is_symmetric,
    is_upper_triangular as is_upper_triangular,
    kronecker_sum_tag as kronecker_sum_tag,
    kronecker_tag as kronecker_tag,
    low_rank_tag as low_rank_tag,
    lower_triangular_tag as lower_triangular_tag,
    negative_semidefinite_tag as negative_semidefinite_tag,
    positive_semidefinite_tag as positive_semidefinite_tag,
    symmetric_tag as symmetric_tag,
    tridiagonal_tag as tridiagonal_tag,
    unit_diagonal_tag as unit_diagonal_tag,
    upper_triangular_tag as upper_triangular_tag,
)


try:
    from gaussx._distributions._mvn import MultivariateNormal as MultivariateNormal
    from gaussx._distributions._mvn_prec import (
        MultivariateNormalPrecision as MultivariateNormalPrecision,
    )
except ModuleNotFoundError as _e:
    if _e.name != "numpyro":
        raise
